#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-collabora-update';

event_actions($event, qw(
             initialize-default-databases 00
             nethserver-collabora-conf 20
));

event_services($event, qw(
               httpd reload
));
