#!/usr/bin/perl -w
#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);

$event = 'certificate-update';
event_actions($event, qw(
             nethserver-collabora-set-wopi-url 91
));


my $event = 'nethserver-collabora-update';
event_actions($event, qw(
             initialize-default-databases 00
             nethserver-collabora-conf 20
             nethserver-collabora-set-wopi-url 91
             nethserver-collabora-restart-loolwsd 99
));

event_templates($event, qw(
  /etc/httpd/conf.d/zz_collabora.conf
  /etc/hosts
));

event_services($event, qw(
               httpd reload
               dnsmasq restart
));


$event = 'nethserver-nextcloud-update';
event_actions($event, qw(
             nethserver-collabora-conf 70
             nethserver-collabora-set-wopi-url 91
));

$event = 'nethserver-nextcloud-save';
event_actions($event, qw(
             nethserver-collabora-conf 70
             nethserver-collabora-set-wopi-url 91
));