#!/bin/bash
#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#


# Disable ssl
/usr/bin/loolconfig set ssl.enable  false
/usr/bin/loolconfig set ssl.termination  true
/usr/bin/loolconfig set net.listen loopback
/usr/bin/loolconfig set net.proto IPv4


#Generate a list of hosts that can access to the wopi storage
#Server FQDN
AllowWopiHosts=`/usr/bin/hostname`

#Nextcloud virtualhost
if [[ -n `/sbin/e-smith/config getprop nextcloud VirtualHost` ]]; then 
    AllowWopiHosts+="|`/sbin/e-smith/config getprop nextcloud VirtualHost`"
fi

#Additional external host
if [[ -n `/sbin/e-smith/config getprop loolwsd AllowWopiHost` ]]; then 
    AllowWopiHosts+="|`/sbin/e-smith/config getprop loolwsd AllowWopiHost`"
fi

/usr/bin/loolconfig set storage.wopi.host "$AllowWopiHosts"

#Install Nethserver-Nextcloud app
if [[ -x "/usr/local/sbin/occ" ]]; then
    /usr/local/sbin/occ app:install richdocuments
    /usr/local/sbin/occ app:enable richdocuments
fi
