#!/bin/bash

# Get domain from prop or use DomainName
if [[ -n `config getprop loolwsd Domain` ]]; then domain=`config getprop loolwsd Domain`; else domain=`config get DomainName`; fi

# FIXME - Create cert if not already there -  cert should not be needed as we do reverse proxy
if [ ! -f /etc/loolwsd/privatekey.pem ]; then openssl genrsa -out /etc/loolwsd/privatekey.pem 4096; fi
if [ ! -f /etc/loolwsd/fullchain.pem ]; then openssl req -batch -new -x509 -sha512 -days 3650 -key /etc/loolwsd/privatekey.pem -out /etc/loolwsd/fullchain.pem; fi

# Configuration with loolconfig
loolconfig set ssl.cert_file_path /etc/loolwsd/fullchain.pem
loolconfig set ssl.key_file_path /etc/loolwsd/privatekey.pem
loolconfig set ssl.ca_file_path ''
loolconfig set storage.wopi.host `echo $domain`

# Set admin user for the web console
sed -i 's!enabled."/>!enabled.">admin</username>!' /etc/loolwsd/loolwsd.xml

# Set default admin password to Nethesis,1234 if not set
if grep -q '<secure_password desc="' /etc/loolwsd/loolwsd.xml; then
  echo 'admin password already set'
else
  yes | loolconfig set-admin-password
  loolconfig set admin_console.secure_password pbkdf2.sha512.10000.84de78d224a447158478da8b9717c3b66ac842e7217ac6b79bf864cf2cbc2d0be5b76818dd397502286295f8d31742564e0b31efac46fb6dffb6bd10ac9aacd1861af5c3311c749bc046608ee47d86f2978eedf78819bbde26e620d886eed4192234517ff15$
fi

# Install nextcloud collabora richdocuments app
sudo -u apache /opt/rh/rh-php71/root/usr/bin/php /usr/share/nextcloud/occ app:install richdocuments

# Set wopi_url
sudo -u apache /opt/rh/rh-php71/root/usr/bin/php /usr/share/nextcloud/occ config:app:set richdocuments wopi_url --value=https:\/\/`echo $domain`

# Enable app
sudo -u apache /opt/rh/rh-php71/root/usr/bin/php /usr/share/nextcloud/occ app:enable richdocuments
