#!/bin/bash
#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#


#Configure WopiUrl for Nethserver-Nextcloud
if [[ -x "/usr/local/sbin/occ" ]]; then

    if [[ -n `/sbin/e-smith/config getprop loolwsd VirtualHost` ]]; then
        WopiUrl=`/sbin/e-smith/config getprop loolwsd VirtualHost`
    else
        WopiUrl=collabora.`/sbin/e-smith/config get DomainName`
    fi

    /usr/local/sbin/occ config:app:set richdocuments wopi_url --value=https://$WopiUrl
    
    /usr/bin/curl https://$WopiUrl > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        /usr/local/sbin/occ config:app:set richdocuments disable_certificate_verification --value=''
    else
        /usr/local/sbin/occ config:app:set richdocuments disable_certificate_verification --value=yes
    fi
    
    /usr/local/sbin/occ richdocuments:activate-config
    
fi
